### PR TITLE
Client Manual Refactoring

### PR DESCRIPTION
**Pull request by ConsoleTVs**
Manual refactoring of the client to meet some of the standards and clean up the code.

**This pull request has NOT been tested, therefore, manual testing is required.**

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
@daleu

**Comment by AlbertSuarez** [comment]
We'll take a look @ConsoleTVs . Thanks a lot for your contribution! 🙌

**Review by AlbertSuarez — CHANGES_REQUESTED** [review]
I've built it and something change with the next/back buttons because they don't show now. Please find an image attached below:

image

Feel free to update your PR with the needed changes for that.

Thanks anyways!

**Comment by ConsoleTVs** [comment]
The CSS is a bit messy in here.
image

And aparently, the footer is there, but somehow hidden:

image

May you guys take a look at it when you have some free time? btw; I also removed dozens of TS warnings.

**Review by daleu — APPROVED** [review]

**Pull request closed without merging**
